freebsd_instance:
  image_family: freebsd-13-2

caldav_unikernel_task:
  pkg_install_script: pkg install -y ocaml-opam gmake bash
  ocaml_script: opam init -a --comp=4.14.2
  mirage_script: eval `opam env` && opam install --confirm-level=unsafe-yes "mirage>=4.5.0"
  configure_script: eval `opam env` && cd mirage && mirage configure -t hvt
  depend_script: eval `opam env` && cd mirage && gmake depend
  copy_script: rm -rf mirage/duniverse/caldav/* && cp -R dune-project caldav.opam src ocaml-webmachine mirage/duniverse/caldav/
  build_script: eval `opam env` && cd mirage && gmake build
  client_artifacts:
    path: mirage/dist/caldav.hvt
